### PR TITLE
chore: Ready to Publish to pub.dev

### PR DESCRIPTION
**Pull request by CurtlyCritchlow**
**- What I did**

- Merged the at_radial_gauges and at_linear_gauges as one package.

- Prepared repo for publishing to pub.dev

**- How I did it**

**- How to verify it**

- Run the example app, you will see the SimpleRadialGauge, ScaleRadialGauge and the SimpleLinearGauge
- Open doc/api/index.html in the browser

**- Description for the changelog**

Merged the at_radial_gauges and at_linear_gauges as one package

### CODE REVIEW

**Review by xavierchanth — CHANGES_REQUESTED** [review]
The diff is too large for browsers, I assume the docs folder is dartdoc?
If so pub.dev will generate and host that for us, we don't need to include it in the repo ourselves.

**Comment by CurtlyCritchlow** [comment]
> 



> The diff is too large for browsers, I assume the docs folder is dartdoc? If so pub.dev will generate and host that for us, we don't need to include it in the repo ourselves.

Yes the doc is dartdoc. I'll remove it from the repo thanks.

**Comment by CurtlyCritchlow** [comment]
@XavierChanth I just need you to check if I have the necessary files and folder in keeping with our pub standards. and I removed the doc folder.

**Comment by xavierchanth** [comment]
@CurtlyCritchlow Make sure your .gitignore has the correct contents as well, you may use this one as a reference:
https://github.com/atsign-foundation/at_widgets/blob/trunk/.gitignore

Things like .DS_Store, .metadata, should not be checked in.

**Comment by CurtlyCritchlow** [comment]
@XavierChanth I just copied all the content from the link and added to the .gitignore file. The challenge is that gitignore doesn't remove files already in remote repo.

**Comment by xavierchanth** [comment]
@CurtlyCritchlow try this command: 
```
git rm --cached `git ls-files -i -c --exclude-from=.gitignore`
```
[source](https://stackoverflow.com/questions/13541615/how-to-remove-files-that-are-listed-in-the-gitignore-but-still-on-the-repositor)

**Comment by CurtlyCritchlow** [comment]
@XavierChanth, Thanks it worked.

**Review by xavierchanth — APPROVED** [review]

**Pull request merged**
